import { ChangeEvent, useState } from "react";
import { ArrowRight, Camera, CloudUpload, Palette, Shirt, Sparkles, UserRound } from "lucide-react";

type Concern = "fit" | "colors" | "silhouette" | "styling" | "something_off" | "dont_know" | "body";
type DirectionId = "comfort" | "confidence" | "experiment";
type Direction = { id: DirectionId; name: string; description: string; changes: string[] };
type Analysis = { summary: string; observations: { category: string; text: string }[]; reframe: string };
type Step = "home" | "photo" | "concern" | "loading" | "analysis" | "directions" | "transforming" | "compare" | "final";

const concerns: { id: Concern; label: string; icon: typeof Shirt }[] = [
  { id: "fit", label: "The fit", icon: Shirt }, { id: "colors", label: "The colors", icon: Palette }, { id: "silhouette", label: "The silhouette", icon: UserRound }, { id: "styling", label: "The styling", icon: Sparkles }, { id: "something_off", label: "Something feels off", icon: Sparkles }, { id: "dont_know", label: "I don't know", icon: Sparkles }, { id: "body", label: "It's my body", icon: UserRound },
];
const api = import.meta.env.VITE_API_URL ?? "";
const callApi = async <T,>(path: string, body: object): Promise<T> => {
  const response = await fetch(`${api}${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json();
  if (!response.ok || !data.success) throw new Error(data.error?.message ?? "Something went wrong. Please try again.");
  return data as T;
};

export default function App() {
  const [step, setStep] = useState<Step>("home"); const [image, setImage] = useState(""); const [mimeType, setMimeType] = useState("image/jpeg"); const [concern, setConcern] = useState<Concern>("fit"); const [analysis, setAnalysis] = useState<Analysis>(); const [directions, setDirections] = useState<Direction[]>([]); const [selected, setSelected] = useState<DirectionId>("confidence"); const [afterImage, setAfterImage] = useState(""); const [error, setError] = useState("");
  const choosePhoto = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.match(/^image\/(jpeg|png|webp)$/)) return setError("Choose a JPEG, PNG, or WebP image."); const reader = new FileReader(); reader.onload = () => { setImage(String(reader.result)); setMimeType(file.type); setError(""); }; reader.readAsDataURL(file); };
  const analyze = async () => { if (!image) return setError("Upload an outfit photo first."); setStep("loading"); setError(""); try { const result = await callApi<{ analysis: Analysis; styleDirections: Direction[] }>("/api/mirror/analyze", { image, mimeType, concern }); setAnalysis(result.analysis); setDirections(result.styleDirections); setSelected(result.styleDirections[1]?.id ?? "comfort"); setStep("analysis"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Analysis failed."); setStep("concern"); } };
  const transform = async () => { const direction = directions.find((item) => item.id === selected); if (!direction) return; setStep("transforming"); setError(""); try { const result = await callApi<{ transformation: { image: string } }>("/api/mirror/transform", { image, mimeType, direction: selected, changes: direction.changes }); setAfterImage(result.transformation.image); setStep("compare"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Transformation failed."); setStep("directions"); } };
  const restart = () => { setStep("home"); setImage(""); setAfterImage(""); setAnalysis(undefined); setDirections([]); setError(""); };
  let page: React.ReactNode;
  if (step === "home") page = <section className="closet-copy"><div className="eyebrow rose">WTF / WHAT THE FIT</div><h1 className="display">Your body doesn’t need an algorithm.</h1><p>Sometimes it’s not you. Sometimes it’s just the fit.</p><button className="btn btn-rose" onClick={() => setStep("photo")}>Check My Fit <ArrowRight size={17} /></button></section>;
  else if (step === "photo") page = <section className="screen-content"><div className="eyebrow rose">01 / THE PHOTO</div><h1 className="screen-title display">Show us the fit.</h1><p className="screen-subtitle">We’re looking at the clothes — not judging you.</p><label className="btn btn-primary"><CloudUpload size={18} /> Take or upload a photo<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden onChange={choosePhoto} /></label>{image && <><img className="uploaded-preview" src={image} alt="Your outfit preview" /><button className="btn btn-primary" onClick={() => setStep("concern")}>Continue <ArrowRight size={17} /></button></>}</section>;
  else if (step === "concern") page = <section className="screen-content"><div className="eyebrow rose">02 / THE FEELING</div><h1 className="screen-title display">What’s throwing you off?</h1><div className="concern-grid">{concerns.map(({ id, label, icon: Icon }) => <button key={id} className={`concern-btn ${concern === id ? "active" : ""}`} onClick={() => setConcern(id)}><Icon size={19} /><strong>{label}</strong></button>)}</div>{concern === "body" && <p className="branch-box">It sounds like the discomfort is landing on your body. Let’s experiment with the outfit first.</p>}<button className="btn btn-primary" onClick={analyze}>Read my fit check <ArrowRight size={17} /></button></section>;
  else if (step === "loading" || step === "transforming") page = <section className="loading-wrap"><div><Camera size={34} /><div className="loading-word">{step === "loading" ? "Reading the fit…" : "Keeping you exactly you…"}</div><p>{step === "loading" ? "Looking at the clothes, not judging you." : "Changing the clothes, not the person…"}</p></div></section>;
  else if (step === "analysis" && analysis) page = <section className="screen-content"><div className="eyebrow rose">03 / HERE’S WHAT WE’RE SEEING</div><h1 className="screen-title display">The fit, not you.</h1><article className="analysis-hero"><h2>{analysis.summary}</h2><p>{analysis.reframe}</p></article><div className="analysis-side">{analysis.observations.map((item, index) => <article className="observation" key={index}><strong>{item.category}</strong><p>{item.text}</p></article>)}</div><button className="btn btn-primary" onClick={() => setStep("directions")}>Show the directions <ArrowRight size={17} /></button></section>;
  else if (step === "directions") page = <section className="screen-content"><div className="eyebrow rose">04 / PICK A DIRECTION</div><h1 className="screen-title display">Not a verdict.<br />A different fit.</h1><div className="direction-grid">{directions.map((item) => <button key={item.id} className={`direction-card ${selected === item.id ? "selected" : ""}`} onClick={() => setSelected(item.id)}><strong>{item.name}</strong><p>{item.description}</p><ul>{item.changes.map((change) => <li key={change}>{change}</li>)}</ul></button>)}</div><button className="btn btn-primary" onClick={transform}>Restyle the fit <ArrowRight size={17} /></button></section>;
  else if (step === "compare") page = <section className="screen-content"><div className="eyebrow rose">BEFORE / AFTER</div><h1 className="screen-title display">SAME YOU.<br />DIFFERENT FIT.</h1><p className="screen-subtitle">0 body changes. Just styling.</p><div className="image-compare"><figure><img src={image} alt="Original outfit" /><figcaption>Before</figcaption></figure><figure><img src={afterImage} alt="Restyled outfit" /><figcaption>After</figcaption></figure></div><button className="btn btn-primary" onClick={() => setStep("final")}>Does this feel more like you? <ArrowRight size={17} /></button></section>;
  else page = <section className="screen-content confidence-wrap"><div className="eyebrow rose">THE FINAL WTF</div><h1 className="screen-title display">That’s the fit.</h1><p className="screen-subtitle">Your body wasn’t something to fix. We just changed the conversation around the clothes.</p><div className="stat-strip"><div className="stat"><strong>0</strong><span>body changes</span></div><div className="stat"><strong>100%</strong><span>your choice</span></div></div><button className="btn btn-primary" onClick={restart}>Try Another Fit <ArrowRight size={17} /></button></section>;
  return <main className="wtf-shell"><header className="topbar"><div className="brand"><span className="brand-mark">WTF</span><span className="brand-word">WHAT THE FIT</span></div><span className="mono">CLOTHES, NOT BODIES</span></header>{error && <div className="error-banner">{error}</div>}{page}</main>;
}
