import { useEffect, useRef, useState, type ReactNode } from "react";
import { ArrowRight, Camera, Palette, RotateCcw, Shirt, Sparkles, UserRound } from "lucide-react";

type Concern = "fit" | "colors" | "silhouette" | "styling" | "something_off" | "dont_know" | "body";
type DirectionId = "comfort" | "confidence" | "experiment";
type Direction = { id: DirectionId; name: string; description: string; changes: string[] };
type Analysis = { summary: string; observations: { category: string; text: string }[]; reframe: string };
type Step = "home" | "photo" | "concern" | "loading" | "analysis" | "directions" | "transforming" | "compare" | "final";

const concerns: { id: Concern; label: string; icon: typeof Shirt }[] = [
  { id: "fit", label: "The fit", icon: Shirt }, { id: "colors", label: "The colors", icon: Palette }, { id: "silhouette", label: "The silhouette", icon: UserRound }, { id: "styling", label: "The styling", icon: Sparkles }, { id: "something_off", label: "Something feels off", icon: Sparkles }, { id: "dont_know", label: "I don't know", icon: Sparkles }, { id: "body", label: "It's my body", icon: UserRound },
];
const api = import.meta.env.VITE_API_URL ?? "";
const callApi = async <T,>(path: string, body: object): Promise<T> => {
  const response = await fetch(`${api}${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json();
  if (!response.ok || !data.success) throw new Error(data.error?.message ?? "Something went wrong. Please try again.");
  return data as T;
};

export default function App() {
  const [step, setStep] = useState<Step>("home"); const [image, setImage] = useState(""); const [mimeType, setMimeType] = useState("image/jpeg"); const [concern, setConcern] = useState<Concern>("fit"); const [analysis, setAnalysis] = useState<Analysis>(); const [directions, setDirections] = useState<Direction[]>([]); const [selected, setSelected] = useState<DirectionId>("confidence"); const [afterImage, setAfterImage] = useState(""); const [visualGenerated, setVisualGenerated] = useState(true); const [transformationMessage, setTransformationMessage] = useState(""); const [error, setError] = useState(""); const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream>();
  const stopCamera = () => { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = undefined; };
  useEffect(() => { if (step !== "photo" || image) return; let active = true; navigator.mediaDevices?.getUserMedia({ video: { facingMode: { ideal: "environment" }, width: { ideal: 1080 }, height: { ideal: 1440 } }, audio: false }).then((stream) => { if (!active) return stream.getTracks().forEach((track) => track.stop()); streamRef.current = stream; if (videoRef.current) videoRef.current.srcObject = stream; }).catch(() => setError("Camera access is needed to check your fit. Allow camera access and try again.")); return () => { active = false; stopCamera(); }; }, [step, image]);
  const capturePhoto = () => { const video = videoRef.current; if (!video || !video.videoWidth) return setError("Camera is still loading. Try again in a moment."); const canvas = document.createElement("canvas"); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); setImage(canvas.toDataURL("image/jpeg", .9)); setMimeType("image/jpeg"); stopCamera(); setError(""); };
  const analyze = async () => { if (!image) return setError("Upload an outfit photo first."); setStep("loading"); setError(""); try { const result = await callApi<{ analysis: Analysis; styleDirections: Direction[] }>("/api/mirror/analyze", { image, mimeType, concern }); setAnalysis(result.analysis); setDirections(result.styleDirections); setSelected(result.styleDirections[1]?.id ?? "comfort"); setStep("analysis"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Analysis failed."); setStep("concern"); } };
  const transform = async () => { const direction = directions.find((item) => item.id === selected); if (!direction) return; setStep("transforming"); setError(""); try { const result = await callApi<{ transformation: { image: string; generated: boolean; message: string } }>("/api/mirror/transform", { image, mimeType, direction: selected, changes: direction.changes }); setAfterImage(result.transformation.image); setVisualGenerated(result.transformation.generated); setTransformationMessage(result.transformation.message); setStep("compare"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Transformation failed."); setStep("directions"); } };
  const restart = () => { setStep("home"); setImage(""); setAfterImage(""); setVisualGenerated(true); setTransformationMessage(""); setAnalysis(undefined); setDirections([]); setError(""); };
  let page: ReactNode;
  if (step === "home") page = <section className="closet-copy"><div className="eyebrow rose">WTF / WHAT THE FIT</div><h1 className="display">Your body doesn’t need an algorithm.</h1><p>Sometimes it’s not you. Sometimes it’s just the fit.</p><button className="btn btn-rose" onClick={() => setStep("photo")}>Check My Fit <ArrowRight size={17} /></button></section>;
  else if (step === "photo") page = <section className="screen-content camera-page"><div><div className="eyebrow rose">01 / THE CAMERA</div><h1 className="screen-title display">Show us the fit.</h1><p className="screen-subtitle">We’re looking at the clothes — not judging you.</p></div><div className="live-camera">{image ? <img src={image} alt="Your fit capture" /> : <video ref={videoRef} autoPlay muted playsInline aria-label="Live outfit camera preview" />}<span>LIVE FIT CHECK</span></div>{image ? <div className="camera-actions"><button className="btn btn-soft" onClick={() => { setImage(""); setError(""); }}><RotateCcw size={17} /> Retake</button><button className="btn btn-primary" onClick={() => setStep("concern")}>Continue <ArrowRight size={17} /></button></div> : <button className="btn btn-rose" onClick={capturePhoto}><Camera size={18} /> Capture my fit</button>}</section>;
  else if (step === "concern") page = <section className="screen-content"><div className="eyebrow rose">02 / THE FEELING</div><h1 className="screen-title display">What’s throwing you off?</h1><div className="concern-grid">{concerns.map(({ id, label, icon: Icon }) => <button key={id} className={`concern-btn ${concern === id ? "active" : ""}`} onClick={() => setConcern(id)}><Icon size={19} /><strong>{label}</strong></button>)}</div>{concern === "body" && <p className="branch-box">It sounds like the discomfort is landing on your body. Let’s experiment with the outfit first.</p>}<button className="btn btn-primary" onClick={analyze}>Read my fit check <ArrowRight size={17} /></button></section>;
  else if (step === "loading" || step === "transforming") page = <section className="loading-wrap"><div><Camera size={34} /><div className="loading-word">{step === "loading" ? "Reading the fit…" : "Keeping you exactly you…"}</div><p>{step === "loading" ? "Looking at the clothes, not judging you." : "Changing the clothes, not the person…"}</p></div></section>;
  else if (step === "analysis" && analysis) page = <section className="screen-content"><div className="eyebrow rose">03 / HERE’S WHAT WE’RE SEEING</div><h1 className="screen-title display">The fit, not you.</h1><article className="analysis-hero"><h2>{analysis.summary}</h2><p>{analysis.reframe}</p></article><div className="analysis-side">{analysis.observations.map((item, index) => <article className="observation" key={index}><strong>{item.category}</strong><p>{item.text}</p></article>)}</div><button className="btn btn-primary" onClick={() => setStep("directions")}>Show the directions <ArrowRight size={17} /></button></section>;
  else if (step === "directions") page = <section className="screen-content"><div className="eyebrow rose">04 / PICK A DIRECTION</div><h1 className="screen-title display">Not a verdict.<br />A different fit.</h1><div className="direction-grid">{directions.map((item) => <button key={item.id} className={`direction-card ${selected === item.id ? "selected" : ""}`} onClick={() => setSelected(item.id)}><strong>{item.name}</strong><p>{item.description}</p><ul>{item.changes.map((change) => <li key={change}>{change}</li>)}</ul></button>)}</div><button className="btn btn-primary" onClick={transform}>Restyle the fit <ArrowRight size={17} /></button></section>;
  else if (step === "compare") { const chosenDirection = directions.find((item) => item.id === selected); page = <section className="screen-content"><div className="eyebrow rose">BEFORE / {visualGenerated ? "AFTER" : "STYLE CONCEPT"}</div><h1 className="screen-title display">SAME YOU.<br />DIFFERENT FIT.</h1><p className="screen-subtitle">0 body changes. Just styling.</p>{!visualGenerated && <p className="concept-notice">{transformationMessage}</p>}<div className={`image-compare ${visualGenerated ? "" : "has-concept"}`}><figure><img src={image} alt="Original outfit" /><figcaption>Original fit</figcaption></figure><figure className={`concept-figure direction-${selected}`}><img src={afterImage} alt={visualGenerated ? "AI-restyled outfit" : "Original outfit used for styling concept"} />{!visualGenerated && <div className="concept-overlay"><span>Styling direction</span><strong>{chosenDirection?.name ?? selected}</strong><p>{chosenDirection?.description}</p><ul>{chosenDirection?.changes.map((change) => <li key={change}>{change}</li>)}</ul><div className="concept-swatches"><i /><i /><i /></div></div>}<figcaption>{visualGenerated ? "AI restyle" : "Visual style plan"}</figcaption></figure></div><button className="btn btn-primary" onClick={() => setStep("final")}>Does this feel more like you? <ArrowRight size={17} /></button></section>; }
  else page = <section className="screen-content confidence-wrap"><div className="eyebrow rose">THE FINAL WTF</div><h1 className="screen-title display">That’s the fit.</h1><p className="screen-subtitle">Your body wasn’t something to fix. We just changed the conversation around the clothes.</p><div className="stat-strip"><div className="stat"><strong>0</strong><span>body changes</span></div><div className="stat"><strong>100%</strong><span>your choice</span></div></div><button className="btn btn-primary" onClick={restart}>Try Another Fit <ArrowRight size={17} /></button></section>;
  const progressSteps = ["Capture", "Feeling", "Insights", "Direction", "Result"];
  const progressIndex: Record<Step, number> = { home: -1, photo: 0, concern: 1, loading: 1, analysis: 2, directions: 3, transforming: 3, compare: 4, final: 4 };
  return <main className={`wtf-shell step-${step}`}>
    <header className="topbar">
      <div className="brand"><span className="brand-mark">WTF</span><span className="brand-word">WHAT THE FIT</span></div>
      <span className="mono topbar-tagline">CLOTHES, NOT BODIES</span>
    </header>
    {step !== "home" && <nav className="journey-progress" aria-label="Fit check progress">
      {progressSteps.map((label, index) => <div key={label} className={`journey-step ${index <= progressIndex[step] ? "complete" : ""} ${index === progressIndex[step] ? "current" : ""}`} aria-current={index === progressIndex[step] ? "step" : undefined}><span>{String(index + 1).padStart(2, "0")}</span><strong>{label}</strong></div>)}
    </nav>}
    {error && <div className="error-banner" role="alert" aria-live="polite">{error}</div>}
    <div className="page-stage page-in" key={step}>{page}</div>
  </main>;
}
